# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

gem "rails", github: "rails/rails", branch: "main"
gem "puma", "~> 6.0"
gem "sqlite3"
gem "lookbook", "~> 2.0"

gem "daisyui_components", path: "../"

group :development, :test do
  gem "foreman"
end
